# Generated by Django 4.1.1 on 2022-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000000)),
                ('alias', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
